root: true

env:
  es6: true

globals:
  wx: readonly
  getApp: readonly
  getCurrentPages: readonly
  App: readonly
  Page: readonly
  Component: readonly
  getRegExp: readonly

extends:
  - eslint:recommended
  - plugin:prettier/recommended

plugins:
  - import

ignorePatterns:
  - dist/

rules:
  curly:
    - error
    - multi
    - consistent

  import/consistent-type-specifier-style:
    - error
    - prefer-top-level

  import/dynamic-import-chunkname:
    - error

  import/first:
    - error

  import/newline-after-import:
    - error

  import/no-commonjs:
    - error

  import/no-cycle:
    - error

  # https://github.com/import-js/eslint-plugin-import/issues/2792
  # import/no-duplicates:
  #   - error
  #   - considerQueryString: true
  #     prefer-inline: true

  import/no-named-default:
    - error

  import/order:
    - error
    - alphabetize:
        order: asc
        orderImportKind: asc
      groups:
        - builtin
        - external
        - internal
        - - parent
          - sibling
        - index
        - object
      newlines-between: always

  no-duplicate-imports:
    - off

  no-unmodified-loop-condition:
    - error

  padding-line-between-statements:
    - error
    - blankLine: always
      prev:
        - const
        - let
      next:
        - "*"
    - blankLine: any
      prev:
        - const
        - let
      next:
        - const
        - let
    - blankLine: always
      prev:
        - "*"
      next:
        - return

  sort-imports:
    - error
    - allowSeparatedGroups: false
      ignoreDeclarationSort: true

  prefer-template: error

overrides:
  - files:
      - "*.wxs"

    globals:
      getDate: readonly

    env:
      es6: false
      node: true

    rules:
      curly:
        - error
        - all

      func-names:
        - error
        - never

      func-style:
        - error
        - "declaration"

      import/no-commonjs:
        - off

      import/no-default-export:
        - error

      import/no-named-export:
        - error

      no-var:
        - off

      object-shorthand:
        - error
        - never

      prefer-destructuring:
        - off

      prefer-template:
        - off

  - files:
      - "*.ts"

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:prettier/recommended

    plugins:
      - "@typescript-eslint"

    parserOptions:
      parser: "@typescript-eslint/parser"
      project:
        - "./tsconfig.app.json"
        - "./tsconfig.cloud.json"

    rules:
      "@typescript-eslint/ban-ts-comment":
        - off

      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowTypedFunctionExpressions: true

      "@typescript-eslint/naming-convention":
        - warn
        - filter:
            match: true
            regex: Content-Type
          format: null
          selector:
            - property

        - selector: default
          format:
            - camelCase
          leadingUnderscore: allowSingleOrDouble
          trailingUnderscore: allow

        - selector:
            - variable
          format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          leadingUnderscore: allowSingleOrDouble
          trailingUnderscore: allowSingleOrDouble

        - selector: parameter
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: property
          format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

        - selector: enumMember
          format:
            - PascalCase

      "@typescript-eslint/no-explicit-any":
        - warn
        - ignoreRestArgs: true

      "@typescript-eslint/no-floating-promises":
        - off

      "@typescript-eslint/no-non-null-assertion":
        - off

      "@typescript-eslint/no-unsafe-member-access":
        - warn

      "@typescript-eslint/unbound-method":
        - off

  - files:
      - "*.d.ts"
    rules:
      no-underscore-dangle:
        - off

  - files:
      - scripts/**/*.js
      - .commitlintrc.cjs
      - gulpfile.cjs

    env:
      node: true

    parserOptions:
      sourceType: commonjs
